/**
 * syncSdFoodBank.js
 *
 * Fetches food distribution locations from the San Diego Food Bank's Storepoint API,
 * filters to East County ZIP codes, parses schedules (deterministically where possible,
 * GPT-4o-mini as a fallback), and upserts them as draft posts in Supabase.
 *
 * Run:  node scripts/syncSdFoodBank.js
 *
 * Required environment variables (GitHub Secrets → injected by Actions):
 *   SUPABASE_URL              — Supabase project URL
 *   SUPABASE_SERVICE_ROLE_KEY — service role key (bypasses RLS)
 *   OPENAI_API_KEY            — GPT-4o-mini for schedule parsing
 *
 * One-time Supabase setup (run once in SQL Editor before first sync):
 *   INSERT INTO organizations (name, domain, is_verified)
 *   VALUES ('San Diego Food Bank', 'sandiegofoodbank.org', true)
 *   ON CONFLICT (domain) DO UPDATE SET name = 'San Diego Food Bank', is_verified = true;
 *
 * IMPORTANT — Timezone:
 *   All locations are in San Diego (America/Los_Angeles). GitHub Actions runners
 *   default to UTC, which shifts "today" and weekday math by several hours and
 *   can push calculations onto the wrong calendar day. Set TZ in the workflow
 *   YAML as the primary fix:
 *
 *     jobs:
 *       sync:
 *         runs-on: ubuntu-latest
 *         env:
 *           TZ: America/Los_Angeles
 *
 *   The line below is a belt-and-suspenders backup in case TZ isn't set in the
 *   workflow. It must run before any Date object is created.
 *
 * Note on source_ids and the sync window:
 *   Each run generates a post for every occurrence of a location's schedule
 *   from right now through one month out (see computeWindowEnd) — not just
 *   the single next occurrence. Since this runs on the 1st and 15th, the two
 *   windows overlap by design (1st → next 1st; 15th → next 15th), so the same
 *   specific occurrence is often regenerated by both runs. source_ids include
 *   the occurrence's date (e.g. `sdfb_<id>_thursday_1st_20260806`) so a
 *   repeated occurrence lands on the same row and gets updated, not
 *   duplicated. deactivateVanished() checks at the location level (parsing
 *   the location id back out of source_id), not the exact source_id, since a
 *   post whose date has simply passed out of the window is expected to stop
 *   reappearing without that meaning its location vanished from Storepoint.
 */

process.env.TZ = process.env.TZ || 'America/Los_Angeles'

import { createClient } from '@supabase/supabase-js'

// ─── Configuration ────────────────────────────────────────────────────────────

const STOREPOINT_URL = 'https://api.storepoint.co/v1/16597334723364/locations'
const ORG_DOMAIN = 'sandiegofoodbank.org'
const SOURCE_PREFIX = 'sdfb_'

// Custom field keys for San Diego Food Bank's Storepoint configuration.
// If schedule data stops appearing, re-check these keys in the raw API response.
const CF_SCHEDULE = 'neci8m1ih2'  // "1st and 3rd Thursday of the month 10:00am…"
const CF_RESCHEDULES = '6hqa392kmt'  // "Reschedules: Jan 8. Cancellations: May 7…"
const CF_FOOD_TYPE = 'r9lac8vy2c'  // "25–30 pounds of fresh produce; occasional dry goods."
const CF_ELIGIBILITY = 'cooifgou2h'  // "All are welcome" / eligibility requirements
const CF_INSTRUCTIONS = 't79gvzzldl'  // "Drive-thru only; bring a cart and reusable bags."

// East County San Diego ZIP codes (shared with syncFeedingSanDiego.js).
// Edit this list to expand or restrict the geographic scope.
const EAST_COUNTY_ZIPS = new Set([
  '91901',                              // Alpine
  '91906',                              // Campo
  '91916',                              // Descanso
  '91917',                              // Dulzura
  '91935',                              // Jamul
  '91941', '91942', '91943', '91944',  // La Mesa
  '91945', '91946',                     // Lemon Grove
  '91962',                              // Pine Valley
  '91977', '91978', '91979',           // Spring Valley
  '92019', '92020', '92021',           // El Cajon
  '92040',                              // Lakeside
  '92071',                              // Santee
])

// Ordinal words/numerals used in "Nth <weekday> of the month" phrasing.
const ORDINAL_MAP = {
  '1st': 1, 'first': 1,
  '2nd': 2, 'second': 2,
  '3rd': 3, 'third': 3,
  '4th': 4, 'fourth': 4,
  '5th': 5, 'fifth': 5,
  'last': 'last',
}
const DAY_INDEX = { sunday: 0, monday: 1, tuesday: 2, wednesday: 3, thursday: 4, friday: 5, saturday: 6 }

const MONTH_MAP = {
  jan: 0, january: 0, feb: 1, february: 1, mar: 2, march: 2, apr: 3, april: 3,
  may: 4, jun: 5, june: 5, jul: 6, july: 6, aug: 7, august: 7,
  sep: 8, sept: 8, september: 8, oct: 9, october: 9, nov: 10, november: 10, dec: 11, december: 11,
}

// ─── Supabase client ──────────────────────────────────────────────────────────

const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY  // service role: bypasses RLS for automated writes
)

// ─── Parsing helpers ──────────────────────────────────────────────────────────

/**
 * Splits a Storepoint address string into { address, city, zip }.
 * Handles both formats:
 *   "1234 Main St, El Cajon, CA 92020, US"  (Feeding SD style)
 *   "1234 Main St, El Cajon, CA 92020"       (SDFB style — no trailing ", US")
 */
function parseAddress(full) {
  const match = full?.trim().match(
    /^(.+?),\s*([^,]+),\s*([A-Z]{2})\s+(\d{5}(?:-\d{4})?),?\s*(?:US)?$/i
  )
  if (!match) return { address: full ?? '', city: '', zip: '' }
  return { address: match[1].trim(), city: match[2].trim(), zip: match[4].trim() }
}

/** Safely parses the Storepoint custom_fields JSON string. */
function parseCustomFields(str) {
  if (!str) return {}
  try { return JSON.parse(str) } catch { return {} }
}

/**
 * Normalises and capitalises a comma-separated tag string.
 * Storepoint for SDFB uses lowercase tags like "thursday,neighborhood distribution".
 */
function normaliseTags(tagStr) {
  if (!tagStr) return []
  return tagStr
    .split(',')
    .map(t => t.trim())
    .filter(Boolean)
    .map(t => t.charAt(0).toUpperCase() + t.slice(1))
}

/**
 * Parses a "H:MM AM/PM" or hour-only "H AM/PM" time string (space before am/pm
 * optional). Real SDFB data mixes both — "10:00am" and plain "11 AM" appear
 * in the same field set. Returns { hour, minute } or null.
 */
function parseSingleTime(str) {
  const m = str.trim().match(/^(\d{1,2})(?::(\d{2}))?\s*(AM|PM)$/i)
  if (!m) return null
  let h = parseInt(m[1])
  const min = m[2] ? parseInt(m[2]) : 0
  const ampm = m[3].toUpperCase()
  if (ampm === 'PM' && h !== 12) h += 12
  if (ampm === 'AM' && h === 12) h = 0
  return { hour: h, minute: min }
}

/**
 * Returns the Date of the Nth (or last) occurrence of a given weekday within
 * a specific year/month, or null if that ordinal doesn't exist in that month
 * (e.g. a "5th Thursday" that doesn't occur).
 */
function nthWeekdayOfMonth(year, month, weekdayIndex, ordinal) {
  if (ordinal === 'last') {
    const last = new Date(year, month + 1, 0) // last calendar day of month
    const diff = (last.getDay() - weekdayIndex + 7) % 7
    last.setDate(last.getDate() - diff)
    return last
  }
  const first = new Date(year, month, 1)
  const firstWeekday = first.getDay()
  const dayOffset = (weekdayIndex - firstWeekday + 7) % 7
  const date = 1 + dayOffset + (ordinal - 1) * 7
  const result = new Date(year, month, date)
  if (result.getMonth() !== month) return null // ordinal doesn't exist this month
  return result
}

/**
 * Returns the same-day-next-month Date, used as the far edge of the sync
 * window (e.g. run on the 1st → window ends on next month's 1st; run on the
 * 15th → window ends on next month's 15th). Since this script only ever runs
 * on the 1st or 15th, there's no month-length edge case to worry about here.
 */
function computeWindowEnd(fromDate) {
  const end = new Date(fromDate)
  end.setMonth(end.getMonth() + 1)
  return end
}

/**
 * Returns ALL occurrences of "the Nth <weekday> of the month at H:MM" that
 * fall within [fromDate, untilDate) — not just the next one. Each sync run
 * covers a rolling ~1-month window (see computeWindowEnd), and consecutive
 * runs overlap on purpose: a date generated by one run and re-generated by
 * the next is expected to land on the same source_id and get updated rather
 * than duplicated (source_id includes the date — see locationToPosts).
 * `isBlocked(date)` skips specific cancelled calendar dates.
 */
function allNthWeekdayOccurrencesInWindow(ordinal, weekdayIndex, hour, minute, fromDate, untilDate, isBlocked = () => false) {
  const occurrences = []
  const monthSpan = (untilDate.getFullYear() - fromDate.getFullYear()) * 12
    + (untilDate.getMonth() - fromDate.getMonth()) + 1 // +1 month of buffer for safety

  for (let i = 0; i <= monthSpan; i++) {
    const probe = new Date(fromDate.getFullYear(), fromDate.getMonth() + i, 1)
    const candidate = nthWeekdayOfMonth(probe.getFullYear(), probe.getMonth(), weekdayIndex, ordinal)
    if (!candidate) continue
    candidate.setHours(hour, minute, 0, 0)
    if (candidate <= fromDate) continue
    if (candidate >= untilDate) continue
    if (isBlocked(candidate)) continue
    occurrences.push(candidate)
  }
  return occurrences
}

/** Formats a Date as a compact "YYYYMMDD" key for building stable, date-scoped source_ids. */
function dateKey(date) {
  const y = date.getFullYear()
  const m = String(date.getMonth() + 1).padStart(2, '0')
  const d = String(date.getDate()).padStart(2, '0')
  return `${y}${m}${d}`
}

/**
 * Deterministically parses schedule text made of comma-separated clauses like:
 *   "1st and 3rd Thursday of the month 10:00am, 2nd Tuesday of the month 9:00am - 11:00am"
 *
 * Real SDFB data mixes several phrasings for the same thing, all handled here:
 *   - "of the month" AND "of each month" (used interchangeably)
 *   - "of the month" is sometimes dropped entirely ("4th Thursday from 3:00 PM...")
 *   - start time led by "at", by "from", or by nothing at all
 *   - start/end time separated by a dash OR by the word "to"
 *   - hour-only times with no colon ("11 AM", "9 am - 11 am")
 *   - trailing "until food is gone" / "until food runs out" instead of an end time
 *   - plural weekday names ("1st and 4th Thursdays")
 *
 * Returns { matched: [...], unmatchedText: string }. Each matched entry is
 * { ordinals: [1,3], weekdayIndex, hour, minute, endHour, endMinute, raw }.
 */
function parseOrdinalWeekdaySchedule(scheduleText) {
  const clauseRegex = /^\s*((?:\d+(?:st|nd|rd|th)|first|second|third|fourth|fifth|last)(?:\s*(?:,|and)\s*(?:\d+(?:st|nd|rd|th)|first|second|third|fourth|fifth|last))*)\s+(sunday|monday|tuesday|wednesday|thursday|friday|saturday)s?\s+(?:of (?:the|each) month)?[,;]?\s*(?:from\s+)?(?:at\s+)?(\d{1,2}(?::\d{2})?\s*[AP]M)(?:\s*(?:[-–]|to)\s*(\d{1,2}(?::\d{2})?\s*[AP]M))?\s*(?:(?:or\s+)?until food (?:is gone|runs out))?\s*$/i

  const rawClauses = scheduleText.split(',').map(c => c.trim()).filter(Boolean)
  const matched = []
  const unmatched = []

  for (const clause of rawClauses) {
    const m = clause.match(clauseRegex)
    if (!m) { unmatched.push(clause); continue }

    const ordinalTokens = m[1].split(/\s*(?:,|and)\s*/i).map(t => t.trim().toLowerCase()).filter(Boolean)
    const ordinals = ordinalTokens.map(t => ORDINAL_MAP[t]).filter(o => o !== undefined)
    const weekdayIndex = DAY_INDEX[m[2].toLowerCase()]
    const startTime = parseSingleTime(m[3])
    const endTime = m[4] ? parseSingleTime(m[4]) : null

    if (ordinals.length === 0 || weekdayIndex === undefined || !startTime) {
      unmatched.push(clause)
      continue
    }

    matched.push({
      ordinals,
      weekdayIndex,
      weekdayName: m[2].toLowerCase(),
      hour: startTime.hour,
      minute: startTime.minute,
      endHour: endTime ? endTime.hour : null,
      endMinute: endTime ? endTime.minute : null,
      raw: clause,
    })
  }

  return { matched, unmatchedText: unmatched.join(', ') }
}

/**
 * Extracts specific calendar dates (month + day, optionally year) mentioned
 * anywhere in cancellation text, e.g. "Jan 8", "May 7, 2026". Only meaningful
 * for pure cancellations — see needsAiForReschedule() below for why reschedule
 * text isn't handled this way.
 */
function parseFlaggedDates(text) {
  if (!text) return []
  const regex = /\b(jan|january|feb|february|mar|march|apr|april|may|jun|june|jul|july|aug|august|sep|sept|september|oct|october|nov|november|dec|december)\.?\s+(\d{1,2})(?:,\s*(\d{4}))?\b/gi
  const dates = []
  for (const m of text.matchAll(regex)) {
    dates.push({
      month: MONTH_MAP[m[1].toLowerCase()],
      day: parseInt(m[2]),
      year: m[3] ? parseInt(m[3]) : null,
    })
  }
  return dates
}

/** Checks whether a candidate Date matches any flagged (cancelled) date. */
function isFlaggedDate(date, flaggedDates) {
  return flaggedDates.some(f =>
    date.getMonth() === f.month &&
    date.getDate() === f.day &&
    (f.year === null || date.getFullYear() === f.year)
  )
}

/**
 * True if the text is a clean "nothing to see here" statement — e.g. "No
 * holiday reschedules for 2026", "All distributions will be held on
 * regularly scheduled days" — which is safe to ignore entirely and stay on
 * the deterministic path.
 */
function isNoScheduleChangeText(text) {
  if (!text) return true
  return /^(no\s|all distributions will be held)/i.test(text.trim())
}

/**
 * Decides whether a location's reschedule/cancellation text is too semantically
 * loaded to resolve with simple date-skipping, and should instead go through AI
 * with the full schedule + reschedule text as context.
 *
 * Real examples from your data show two genuinely different things sharing one
 * field:
 *   - "Cancellations: May 7, July 2..." — these dates are skipped outright;
 *     the next regular occurrence is correct. Safe to handle deterministically.
 *   - "Rescheduled to: May 29, Nov 20, Dec 11" — these dates ARE the actual
 *     occurrence for whichever month they replace (e.g. a 4th Friday that fell
 *     on a holiday moved to May 29 instead). Skipping May 29 would be wrong —
 *     it's not a date to avoid, it's the date to use. But matching which
 *     reschedule date belongs to which specific month from text alone isn't
 *     reliable, so rather than guess, the whole location goes to AI, which can
 *     read "the 4th Friday moves to May 29 this month" in context.
 *   - "Cancelled January 2026" / "July Cancelled" — whole-month cancellations
 *     with no specific day, which parseFlaggedDates can't represent at all.
 *     Also needs AI.
 *
 * Clean negations ("No holiday reschedules", "All distributions will be held
 * on regularly scheduled days") are excluded so the common, unremarkable case
 * still gets the more reliable deterministic date math.
 */
function needsAiForReschedule(rescheduleText) {
  if (!rescheduleText) return false
  if (isNoScheduleChangeText(rescheduleText)) return false
  return /reschedul|cancel/i.test(rescheduleText)
}

/**
 * Converts a naive "YYYY-MM-DDTHH:MM:00" string (no offset) — as returned by
 * the AI, meaning America/Los_Angeles local time — into a correct UTC ISO
 * string for storage.
 *
 * Relying on `new Date(str)` alone would be a footgun here: per spec, a
 * date-time string with no offset is parsed in the *local* timezone of the
 * running process, which is only correct because we set TZ=America/Los_Angeles
 * at the top of this file. This function makes that dependency explicit and
 * produces an unambiguous 'Z'-suffixed string so Postgres can't misinterpret
 * it under its own session timezone.
 */
function localIsoToUtcIso(naiveLocalIso) {
  if (!naiveLocalIso) return null
  const d = new Date(naiveLocalIso)
  if (isNaN(d)) return null
  return d.toISOString()
}

/**
 * Calls OpenAI GPT-4o-mini (via built-in fetch, no package needed) to parse a
 * natural-language schedule into every occurrence that falls within the given
 * window — not just the next one, since each sync run needs to populate
 * roughly a month of upcoming events at once (see computeWindowEnd).
 *
 * The tags array is passed as a hint because SDFB includes the day of the week
 * as a tag (e.g. "Thursday"), which helps the model resolve ambiguous schedules.
 *
 * Used only as a fallback when the deterministic ordinal-weekday parser above
 * can't recognize the text — LLMs are unreliable at "Nth weekday of month"
 * calendar arithmetic, so prefer the deterministic parser whenever possible.
 * Costs here are low enough that leaning on this fallback freely (rather than
 * flagging for manual review) is the preferred tradeoff.
 *
 * Returns { parsed: true, occurrences: [{start, end}, ...] } or { parsed: false }.
 */
async function parseScheduleWithAI(scheduleText, locationName, dayHints, rescheduleText, windowStart, windowEnd) {
  if (!process.env.OPENAI_API_KEY) return { parsed: false, occurrences: [] }

  const fmt = d => d.toLocaleDateString('en-US', {
    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric',
    timeZone: 'America/Los_Angeles',
  })
  const today = fmt(new Date())

  const hintLine = dayHints.length
    ? `Day-of-week hints from tags: ${dayHints.join(', ')}`
    : ''

  const closureLine = rescheduleText
    ? `Reschedules/cancellations: "${rescheduleText}"`
    : ''

  const prompt = `You are a precise scheduling assistant for food distribution events.

Today (America/Los_Angeles time): ${today}
Window: from ${fmt(windowStart)} through ${fmt(windowEnd)} (exclusive), America/Los_Angeles time
Location: "${locationName}"
${hintLine}
Schedule: "${scheduleText}"
${closureLine}

List EVERY occurrence of this schedule that falls within the window above (there may be one, several, or none). Rules:
- Return ONLY valid JSON: a JSON array of occurrences, no markdown or explanation
- Each item: {"start":"YYYY-MM-DDTHH:MM:00","end":"YYYY-MM-DDTHH:MM:00"} — all datetimes ISO 8601, local America/Los_Angeles time, no offset
- If the end time is not stated, use null for "end"
- Only include occurrences strictly after "today" above and strictly before the window end
- Convert "10:00am", "9:30 am", "2:00 p.m." etc. correctly to 24-hour format
- Use day-of-week hints to resolve any ambiguity about which day is intended
- If a listed date falls within a stated closure or cancellation period, omit that occurrence entirely
- If a reschedule note gives a specific replacement date for an occurrence in this window, use the replacement date instead of the normally-computed one
- If the schedule text cannot be parsed at all, return {"parsed":false} instead of an array

Example, two occurrences in window: [{"start":"2026-08-06T10:00:00","end":null},{"start":"2026-09-03T10:00:00","end":null}]
Example, none fall in window: []
Example, unparseable: {"parsed":false}`

  try {
    const res = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${process.env.OPENAI_API_KEY}`,
      },
      body: JSON.stringify({
        model: 'gpt-4o-mini',
        messages: [{ role: 'user', content: prompt }],
        response_format: { type: 'json_object' },
        temperature: 0,
        max_tokens: 2000,
      }),
    })
    const json = await res.json()
    const raw = json.choices[0].message.content
    const parsed = JSON.parse(raw)

    if (Array.isArray(parsed)) return { parsed: true, occurrences: parsed }
    // Some JSON-object-mode APIs wrap arrays in a key; handle that shape too.
    if (parsed && Array.isArray(parsed.occurrences)) return { parsed: true, occurrences: parsed.occurrences }
    return { parsed: false, occurrences: [] }
  } catch (err) {
    console.error('    ⚠️  OpenAI API error:', err.message)
    return { parsed: false, occurrences: [] }
  }
}

/**
 * Calls the AI parser on a piece of schedule text and builds one post per
 * occurrence it finds within the window. Used both as the primary fallback
 * (when the deterministic ordinal-weekday parser can't recognize the text at
 * all) and as the secondary fallback (for leftover text, or when reschedule
 * text has semantics too complex for simple date-skipping).
 *
 * source_id includes the occurrence's date (see dateKey()) so that the same
 * specific occurrence — e.g. "August 6, 2026" — gets the same source_id no
 * matter which sync run (1st-of-month or 15th-of-month) generates it. Since
 * the two runs' ~1-month windows overlap, the same occurrence is often
 * regenerated by both; matching source_ids means the second run updates the
 * existing row instead of creating a duplicate.
 *
 * Returns an array of post payloads (zero, one, or many).
 */
async function buildAiParsedPost(loc, text, dayHints, rescheduleText, sharedDesc, base, sourceIdSuffix, windowStart, windowEnd) {
  console.log(`    🤖 AI parsing: "${text}"`)
  const ai = await parseScheduleWithAI(text, loc.name, dayHints, rescheduleText, windowStart, windowEnd)

  if (!ai.parsed) {
    return [{
      ...base,
      source_id: `${SOURCE_PREFIX}${loc.id}_${sourceIdSuffix}`,
      description: [
        '⚠️ REVIEW REQUIRED — Schedule could not be parsed automatically, even by AI.\n' +
        'Please set the date and time manually before publishing.\n\n' +
        `Raw schedule: ${text}`,
        sharedDesc,
      ].filter(Boolean).join('\n\n'),
      start_time: null,
      end_time: null,
    }]
  }

  // Defensive filter: trust the prompt, but don't let a minor AI boundary
  // mistake create a post outside the intended window.
  const inWindow = ai.occurrences.filter(occ => {
    if (!occ?.start) return false
    const d = new Date(occ.start) // naive local string, interpreted as America/Los_Angeles per TZ set at top of file
    return !isNaN(d) && d > windowStart && d < windowEnd
  })

  if (inWindow.length === 0) {
    // Parsed fine, but nothing falls in this window (e.g. seasonal pause) — informational, not an error.
    return [{
      ...base,
      source_id: `${SOURCE_PREFIX}${loc.id}_${sourceIdSuffix}`,
      description: [`📅 Schedule\n${text}\n\n(No occurrences fall within the current sync window.)`, sharedDesc]
        .filter(Boolean).join('\n\n'),
      start_time: null,
      end_time: null,
    }]
  }

  return inWindow.map(occ => {
    const startIso = localIsoToUtcIso(occ.start)
    const endIso = localIsoToUtcIso(occ.end)
    const key = dateKey(new Date(occ.start))
    return {
      ...base,
      source_id: `${SOURCE_PREFIX}${loc.id}_${sourceIdSuffix}_${key}`,
      description: [`📅 Schedule\n${text}`, sharedDesc].filter(Boolean).join('\n\n'),
      start_time: startIso,
      end_time: endIso,
    }
  })
}

// ─── Location → post payload(s) ───────────────────────────────────────────────

/**
 * Converts one Storepoint location into one or more post payloads, covering
 * every occurrence of its schedule within [windowStart, windowEnd).
 *
 * SDFB locations never have structured day/hour Storepoint fields (unlike
 * Feeding SD) — all schedule data lives in the CF_SCHEDULE custom field as
 * text, so every location goes through one of:
 *   A) "Nth <weekday> of the month" text, deterministically parsed → one post
 *      per occurrence per ordinal/weekday/time clause (real date math, no AI
 *      guessing) — a clause can produce multiple posts if the window spans
 *      more than one occurrence of it
 *   B) Anything A doesn't fully recognize (unusual phrasing, leftover text
 *      alongside clauses A did match, or reschedule text too complex for
 *      simple date-skipping) → AI-parsed occurrences, using day-of-week tags
 *      as a disambiguation hint
 *   C) No schedule text at all → one post, flagged for review (nothing to
 *      hand the AI either)
 */
async function locationToPosts(loc, orgId, windowStart, windowEnd) {
  const addr = parseAddress(loc.streetaddress)
  const cf = parseCustomFields(loc.custom_fields)

  const scheduleText = (cf[CF_SCHEDULE] ?? '').trim()
  const rescheduleText = (cf[CF_RESCHEDULES] ?? '').trim()
  const foodType = (cf[CF_FOOD_TYPE] ?? '').trim()
  const eligibility = (cf[CF_ELIGIBILITY] ?? '').trim()
  const instructions = (cf[CF_INSTRUCTIONS] ?? '').trim()

  // Normalise tags and extract day-of-week values as AI hints
  const rawTags = normaliseTags(loc.tags)
  const dayNames = new Set(['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'])
  const dayHints = rawTags.filter(t => dayNames.has(t))

  // Strip day-of-week tags and internal program codes (e.g. EFAP) — meaningless to public visitors
  const STRIP_TAGS = new Set([...dayNames, 'Efap', 'EFAP', 'efap'])
  const cleanTags = rawTags.filter(t => !STRIP_TAGS.has(t))
  const tags = [...new Set([...cleanTags, 'San Diego Food Bank'])]

  const flaggedDates = parseFlaggedDates(rescheduleText)

  // Shared description sections appended to every post from this location
  const sharedLines = []
  if (foodType) sharedLines.push(`🥕 Food Provided\n${foodType}`)
  if (eligibility) sharedLines.push(`✅ Eligibility\n${eligibility}`)
  if (instructions) sharedLines.push(`ℹ️ Service Instructions\n${instructions}`)
  if (rescheduleText) sharedLines.push(`⚠️ Closures & Reschedules\n${rescheduleText}`)
  const sharedDesc = sharedLines.join('\n\n')

  const base = {
    organization_id: orgId,
    title: loc.name,
    location_name: loc.name,
    address: addr.address,
    city: addr.city,
    zip: addr.zip,
    latitude: loc.loc_lat || null,
    longitude: loc.loc_long || null,
    category: 'food-distribution',
    tags,
    // Phone in its own column so the feed renders it as a tap-to-call link
    organizer_phone: loc.phone?.trim() || null,
    // SD Food Bank logo — same image used in the partner org box on the public feed
    image_url: 'https://www.vikingcold.com/wp-content/uploads/2019/11/san-diego-food-bank.png',
    is_active: true,
    is_recurring: false,
    // Published immediately so posts appear on the live feed after sync
    status: 'published',
  }

  const posts = []

  // ── "Nth <weekday> of the month" — parsed deterministically ────────────────
  if (scheduleText) {
    const { matched, unmatchedText } = parseOrdinalWeekdaySchedule(scheduleText)
    const rescheduleNeedsAi = needsAiForReschedule(rescheduleText)

    if (matched.length > 0 && rescheduleNeedsAi) {
      // The recurring pattern parsed fine, but the reschedule/cancellation text
      // has semantics (a specific replacement date, a whole-month cancellation)
      // that simple date-skipping can't safely resolve — see needsAiForReschedule().
      // Hand the whole thing to AI with full context rather than risk a wrong date.
      console.log(`    🤖 Pattern matched, but reschedule text needs interpretation — sending to AI: "${rescheduleText}"`)
      posts.push(...await buildAiParsedPost(loc, scheduleText, dayHints, rescheduleText, sharedDesc, base, 'custom', windowStart, windowEnd))
      return posts
    }

    if (matched.length > 0) {
      console.log(`    🗓️  Deterministically parsed ${matched.length} schedule clause(s)`)

      for (const clause of matched) {
        for (const ordinal of clause.ordinals) {
          const occurrences = allNthWeekdayOccurrencesInWindow(
            ordinal, clause.weekdayIndex, clause.hour, clause.minute,
            windowStart, windowEnd,
            candidate => isFlaggedDate(candidate, flaggedDates)
          )
          if (occurrences.length === 0) {
            console.log(`    ⚠️  No occurrence for "${ordinal}" ${clause.weekdayName} falls within this window — skipping`)
            continue
          }

          const ordinalLabel = ordinal === 'last' ? 'last' : { 1: '1st', 2: '2nd', 3: '3rd', 4: '4th', 5: '5th' }[ordinal]
          const weekdayLabel = clause.weekdayName.charAt(0).toUpperCase() + clause.weekdayName.slice(1)

          for (const startDt of occurrences) {
            let endDt = null
            if (clause.endHour !== null) {
              endDt = new Date(startDt)
              endDt.setHours(clause.endHour, clause.endMinute, 0, 0)
            }

            const descLines = [`📅 Schedule\nRecurring: ${ordinalLabel} ${weekdayLabel} of the month — ${clause.raw}.`]
            if (sharedDesc) descLines.push(sharedDesc)

            posts.push({
              ...base,
              // Date-scoped so this specific occurrence keeps the same source_id
              // across overlapping sync-run windows (see buildAiParsedPost's comment).
              source_id: `${SOURCE_PREFIX}${loc.id}_${clause.weekdayName}_${ordinalLabel}_${dateKey(startDt)}`,
              description: descLines.join('\n\n'),
              start_time: startDt.toISOString(),
              end_time: endDt ? endDt.toISOString() : null,
            })
          }
        }
      }

      // Leftover text the deterministic parser didn't recognize → AI, not a review flag
      if (unmatchedText) {
        posts.push(...await buildAiParsedPost(loc, unmatchedText, dayHints, rescheduleText, sharedDesc, base, 'custom', windowStart, windowEnd))
      }

      return posts
    }

    // Nothing matched deterministically at all — hand the whole string to AI
    posts.push(...await buildAiParsedPost(loc, scheduleText, dayHints, rescheduleText, sharedDesc, base, 'custom', windowStart, windowEnd))
    return posts
  }

  // ── No schedule text at all — nothing to parse, flag for review ────────────
  const descLines = [
    '⚠️ REVIEW REQUIRED — No schedule information could be determined.\n' +
    'Please set the date and time manually before publishing.',
  ]
  if (sharedDesc) descLines.push(sharedDesc)

  posts.push({
    ...base,
    source_id: `${SOURCE_PREFIX}${loc.id}_custom`,
    description: descLines.join('\n\n'),
    start_time: null,
    end_time: null,
  })
  return posts
}

// ─── Database operations ──────────────────────────────────────────────────────

/**
 * Upserts a single post.
 *
 * Duplicate rules:
 *   1. Same source_id           → update (admin's status and is_active are preserved).
 *   2. Same address + start_time → skip (always a duplicate, regardless of source).
 *
 * Returns: 'new' | 'updated' | 'skipped'
 */
async function upsertPost(post) {

  // ── Duplicate guard: address + start_time collision with a different source ──
  if (post.start_time) {
    const { data: dupe } = await supabase
      .from('posts')
      .select('id, title, source_id')
      .eq('address', post.address)
      .eq('start_time', post.start_time)
      .neq('source_id', post.source_id)
      .maybeSingle()

    if (dupe) {
      console.log(`    ⏩ Skipped — duplicate of "${dupe.title}" (same address + time)`)
      return 'skipped'
    }
  }

  // ── Check for existing record by source_id ──────────────────────────────────
  const { data: existing } = await supabase
    .from('posts')
    .select('id, status, is_active')
    .eq('source_id', post.source_id)
    .maybeSingle()

  if (existing) {
    // UPDATE: refresh data fields but preserve admin's status and is_active decisions.
    const { status, is_active, ...dataFields } = post
    const { error } = await supabase
      .from('posts')
      .update(dataFields)
      .eq('id', existing.id)

    if (error) {
      console.error(`    ✗ Update failed [${post.source_id}]:`, error.message)
      return 'skipped'
    }
    console.log(`    ↻ Updated: ${post.title}`)
    return 'updated'
  }

  // INSERT: brand-new post, always starts as draft
  const { error } = await supabase.from('posts').insert(post)
  if (error) {
    console.error(`    ✗ Insert failed [${post.source_id}]:`, error.message)
    return 'skipped'
  }
  console.log(`    ✨ New post: ${post.title}`)
  return 'new'
}

/** Extracts the Storepoint location id embedded at the start of a source_id. */
function extractLocationId(sourceId) {
  const rest = sourceId.slice(SOURCE_PREFIX.length)
  const idx = rest.indexOf('_')
  return idx === -1 ? rest : rest.slice(0, idx)
}

/**
 * Deactivates SDFB posts that no longer belong on the live feed, for two
 * distinct reasons:
 *
 *   1. VANISHED — the location itself is no longer in the current Storepoint
 *      batch (left the Food Bank's network entirely).
 *
 *   2. STALE — the location still exists, but THIS specific post wasn't
 *      regenerated by the current run, and it isn't simply a past event that
 *      aged out of the window naturally. This catches posts left behind by
 *      an old naming scheme (e.g. `sdfb_<id>` from before source_ids were
 *      date-scoped) that will never be regenerated or updated under the new
 *      scheme, as well as an occurrence that got superseded (e.g. a
 *      cancellation/reschedule that changed which date applies). A post
 *      whose start_time is already in the past relative to this run's window
 *      is left alone — that's expected aging, not staleness.
 */
async function deactivateVanished(processedLocationIds, processedPostIds, windowStart) {
  const { data: activeSdfb, error } = await supabase
    .from('posts')
    .select('id, source_id, title, description, start_time')
    .like('source_id', `${SOURCE_PREFIX}%`)
    .eq('is_active', true)

  if (error) {
    console.error('  ✗ Could not fetch existing SDFB posts:', error.message)
    return 0
  }

  const stale = (activeSdfb ?? []).filter(p => {
    const locationVanished = !processedLocationIds.has(extractLocationId(p.source_id))
    if (locationVanished) return true
    if (processedPostIds.has(p.source_id)) return false // regenerated this run — still current
    if (p.start_time && new Date(p.start_time) < windowStart) return false // already happened — expected aging, not stale
    return true // location is active, but this exact post wasn't regenerated and isn't a past event
  })

  if (stale.length === 0) { console.log('  ✓ No vanished or stale posts.'); return 0 }

  const runDate = new Date().toLocaleDateString('en-US', {
    month: 'long', day: 'numeric', year: 'numeric',
  })

  for (const post of stale) {
    const locationVanished = !processedLocationIds.has(extractLocationId(post.source_id))
    const notice = locationVanished
      ? `[Auto-deactivated ${runDate} — location no longer in San Diego Food Bank's directory.]`
      : `[Auto-deactivated ${runDate} — superseded by updated sync data (old source_id format or a changed occurrence). If this looks wrong, check the location's current schedule.]`
    const { error: err } = await supabase
      .from('posts')
      .update({
        is_active: false,
        description: `${notice}\n\n${post.description ?? ''}`.trim(),
      })
      .eq('id', post.id)

    if (err) console.error(`  ✗ Deactivate failed for "${post.title}":`, err.message)
    else console.log(`  🗑️  Deactivated (${locationVanished ? 'vanished' : 'stale'}): ${post.title} [${post.source_id}]`)
  }

  return stale.length
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  console.log(`\n${'─'.repeat(60)}`)
  console.log(`🔄  San Diego Food Bank sync — ${new Date().toLocaleString()}`)
  console.log(`${'─'.repeat(60)}\n`)

  // Validate required environment variables
  const missing = ['SUPABASE_URL', 'SUPABASE_SERVICE_ROLE_KEY'].filter(k => !process.env[k])
  if (missing.length) {
    console.error('❌  Missing required environment variables:', missing.join(', '))
    process.exit(1)
  }
  if (!process.env.OPENAI_API_KEY) {
    console.warn('⚠️   OPENAI_API_KEY not set — schedules that need AI parsing will be flagged for manual review.\n')
  }

  // ── 1. Look up the San Diego Food Bank org in Supabase ─────────────────────
  console.log(`🏢  Looking up "${ORG_DOMAIN}" organization…`)
  const { data: org, error: orgErr } = await supabase
    .from('organizations')
    .select('id, name')
    .eq('domain', ORG_DOMAIN)
    .single()

  if (orgErr || !org) {
    console.error(`❌  Organization not found for domain "${ORG_DOMAIN}".`)
    console.error('    Run this SQL in Supabase first:')
    console.error(`    INSERT INTO organizations (name, domain, is_verified)`)
    console.error(`    VALUES ('San Diego Food Bank', '${ORG_DOMAIN}', true)`)
    console.error(`    ON CONFLICT (domain) DO UPDATE SET is_verified = true;`)
    process.exit(1)
  }
  console.log(`    Found: "${org.name}" (${org.id})\n`)

  // ── 2. Fetch all locations from Storepoint ──────────────────────────────────
  console.log('📡  Fetching from Storepoint API…')
  const res = await fetch(STOREPOINT_URL)
  if (!res.ok) {
    console.error(`❌  Storepoint API returned HTTP ${res.status}`)
    process.exit(1)
  }
  const { results } = await res.json()
  const allLocations = results?.locations ?? []
  console.log(`    ${allLocations.length} total locations received`)

  // ── 3. Filter to East County ZIP codes ─────────────────────────────────────
  const eastCounty = allLocations.filter(loc => {
    const { zip } = parseAddress(loc.streetaddress)
    return EAST_COUNTY_ZIPS.has(zip)
  })
  console.log(`    ${eastCounty.length} East County locations after ZIP filter\n`)

  // ── 4. Compute the sync window ──────────────────────────────────────────────
  // Every occurrence from right now through one month out gets a post — not
  // just the single next one. Running on the 1st and 15th means these windows
  // overlap by design; the overlap is resolved by upsert (same source_id).
  const windowStart = new Date()
  const windowEnd = computeWindowEnd(windowStart)
  console.log(`🗓️  Sync window: ${windowStart.toLocaleDateString('en-US', { timeZone: 'America/Los_Angeles' })} → ${windowEnd.toLocaleDateString('en-US', { timeZone: 'America/Los_Angeles' })}\n`)

  // ── 5. Process each location ────────────────────────────────────────────────
  const processedLocationIds = new Set(eastCounty.map(loc => String(loc.id)))
  const processedPostIds = new Set()
  const counts = { new: 0, updated: 0, skipped: 0 }

  for (const loc of eastCounty) {
    console.log(`📍  ${loc.name}  (${loc.streetaddress})`)

    let posts
    try {
      posts = await locationToPosts(loc, org.id, windowStart, windowEnd)
    } catch (err) {
      console.error(`    ✗ Error building post for ${loc.name}:`, err.message)
      continue
    }

    if (posts.length === 0) {
      console.log('    ⚠️  No valid slots found — location skipped')
      continue
    }

    for (const post of posts) {
      processedPostIds.add(post.source_id)
      const result = await upsertPost(post)
      counts[result]++
    }
  }

  // ── 6. Deactivate vanished locations ────────────────────────────────────────
  console.log('\n🧹  Checking for vanished locations and stale posts…')
  const deactivated = await deactivateVanished(processedLocationIds, processedPostIds, windowStart)

  // ── 7. Summary ──────────────────────────────────────────────────────────────
  console.log(`\n${'─'.repeat(60)}`)
  console.log('✅  Sync complete\n')
  console.log(`    ${eastCounty.length} East County locations processed`)
  console.log(`    ${processedPostIds.size} total post slots evaluated`)
  console.log(`    ${counts.new}       new draft posts created`)
  console.log(`    ${counts.updated}   existing posts refreshed`)
  console.log(`    ${counts.skipped}   skipped (duplicates or errors)`)
  console.log(`    ${deactivated}      deactivated (vanished locations or stale posts)`)
  console.log(`${'─'.repeat(60)}\n`)
}

main().catch(err => {
  console.error('\n❌  Fatal error:', err)
  process.exit(1)
})