/**
 * syncFeedingSanDiego.js
 *
 * Fetches food distribution locations from Feeding San Diego's Storepoint API,
 * filters to East County ZIP codes, and upserts them as draft posts in Supabase.
 *
 * Run:  node scripts/syncFeedingSanDiego.js
 *
 * Required environment variables (GitHub Secrets → injected by Actions):
 *   SUPABASE_URL              — Supabase project URL
 *   SUPABASE_SERVICE_ROLE_KEY — service role key (bypasses RLS)
 *   OPENAI_API_KEY            — GPT-4o-mini for natural-language schedule parsing
 *
 * IMPORTANT — Timezone:
 *   All locations are in San Diego (America/Los_Angeles). GitHub Actions runners
 *   default to UTC, which shifts "today" and weekday math by several hours and
 *   can push calculations onto the wrong calendar day. Set TZ in the workflow
 *   YAML as the primary fix:
 *
 *     jobs:
 *       sync:
 *         runs-on: ubuntu-latest
 *         env:
 *           TZ: America/Los_Angeles
 *
 *   The line below is a belt-and-suspenders backup in case TZ isn't set in the
 *   workflow. It must run before any Date object is created.
 *
 * Note on source_ids and the sync window:
 *   Each run generates a post for every occurrence of a location's schedule
 *   from right now through one month out (see computeWindowEnd) — not just
 *   the single next occurrence. Since this runs on the 1st and 15th, the two
 *   windows overlap by design (1st → next 1st; 15th → next 15th), so the same
 *   specific occurrence is often regenerated by both runs. source_ids include
 *   the occurrence's date so a repeated occurrence lands on the same row and
 *   gets updated, not duplicated. deactivateVanished() checks at the location
 *   level (parsing the location id back out of source_id), not the exact
 *   source_id, since a post whose date has simply passed out of the window is
 *   expected to stop reappearing without that meaning its location vanished
 *   from Storepoint.
 */

process.env.TZ = process.env.TZ || 'America/Los_Angeles'

import { createClient } from '@supabase/supabase-js'

// ─── Configuration ────────────────────────────────────────────────────────────

const STOREPOINT_URL = 'https://api.storepoint.co/v1/16765f3e46d5c1/locations'
const FEEDING_SD_ORG_ID = 'c971ded9-2faa-40d2-b1dd-862a19839120'
const SOURCE_PREFIX = 'fsd_'

// Storepoint custom-field IDs for Feeding San Diego.
// If schedule data stops appearing, re-check these keys in the raw API response.
const CF_SCHEDULE = 'l9y291xrn5'  // "2nd and 4th Wednesday of the month from 12:00 - 2:00 PM"
const CF_CLOSURES = 'bqk2r0h4g4j' // "Closed 7/1/26 to 8/17/26." / "Rescheduled to 9/14/26" / etc.
const CF_ELIGIBILITY = 'ppmuccyqra'  // "By appointment only" / "Residents of 92123 zip code only" / etc.

// East County San Diego ZIP codes.
// Edit this list to expand or restrict the geographic scope.
const EAST_COUNTY_ZIPS = new Set([
  '91901',                              // Alpine
  '91906',                              // Campo
  '91916',                              // Descanso
  '91917',                              // Dulzura
  '91935',                              // Jamul
  '91941', '91942', '91943', '91944',  // La Mesa
  '91945', '91946',                     // Lemon Grove
  '91962',                              // Pine Valley
  '91977', '91978', '91979',           // Spring Valley
  '92019', '92020', '92021',           // El Cajon
  '92040',                              // Lakeside
  '92071',                              // Santee
])

const DAY_FIELDS = ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday']
const DAY_INDEX = { sunday: 0, monday: 1, tuesday: 2, wednesday: 3, thursday: 4, friday: 5, saturday: 6 }

// Ordinal words/numerals used in "Nth <weekday> of the month" phrasing.
const ORDINAL_MAP = {
  '1st': 1, 'first': 1,
  '2nd': 2, 'second': 2,
  '3rd': 3, 'third': 3,
  '4th': 4, 'fourth': 4,
  '5th': 5, 'fifth': 5,
  'last': 'last',
}

// ─── Supabase client ──────────────────────────────────────────────────────────

const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY  // service role: bypasses RLS for automated writes
)

// ─── Parsing helpers ──────────────────────────────────────────────────────────

/**
 * Splits a Storepoint address string into { address, city, zip }.
 * Input format: "1234 Main St, El Cajon, CA 92020, US"
 */
function parseAddress(full) {
  const match = full?.trim().match(
    /^(.+?),\s*([^,]+),\s*([A-Z]{2})\s+(\d{5}(?:-\d{4})?),?\s*US$/i
  )
  if (!match) return { address: full ?? '', city: '', zip: '' }
  return { address: match[1].trim(), city: match[2].trim(), zip: match[4].trim() }
}

/** Safely parses the Storepoint custom_fields JSON string. */
function parseCustomFields(str) {
  if (!str) return {}
  try { return JSON.parse(str) } catch { return {} }
}

/**
 * Parses a single "H:MM[:SS] [AM|PM]" time token. Minutes, seconds, and the
 * meridiem are all individually optional here — real data includes bare hours
 * ("10 AM"), seconds ("3:45:00 PM"), and times with no AM/PM at all when
 * paired with a sibling time that does have one (resolved by the caller via
 * meridiem-borrowing — see parseTimeRangesInField and parseOrdinalWeekdaySchedule).
 */
function parseTimeToken(str) {
  const m = str.trim().match(/^(\d{1,2})(?::(\d{2}))?(?::\d{2})?\s*(AM|PM)?$/i)
  if (!m) return null
  return { hour: parseInt(m[1]), minute: m[2] ? parseInt(m[2]) : 0, meridiem: m[3] ? m[3].toUpperCase() : null }
}

/** Converts a 1-12 hour + AM/PM meridiem into 24-hour form. */
function resolveHour(hour, meridiem) {
  let h = hour
  if (meridiem === 'PM' && h !== 12) h += 12
  if (meridiem === 'AM' && h === 12) h = 0
  return h
}

/**
 * Parses a Storepoint day field into one or more {startHour, startMinute,
 * endHour, endMinute} ranges. Real data has locations with MULTIPLE ranges in
 * one field, comma-separated (e.g. "8:30 AM - 10:30 AM, 11:15 AM - 2:00 PM"),
 * and ranges where only one side states AM/PM (e.g. "9:00 AM - 1:00 PM, 5:00 -
 * 7:00 PM" — the "5:00" borrows PM from the "7:00 PM" beside it). The original
 * single-range parser silently dropped every field shaped like this.
 */
function parseTimeRangesInField(fieldStr) {
  const parts = fieldStr.split(',').map(s => s.trim()).filter(Boolean)
  const ranges = []
  for (const part of parts) {
    const m = part.match(/^(\d{1,2}:\d{2}(?::\d{2})?\s*(?:AM|PM)?)\s*[-–]\s*(\d{1,2}:\d{2}(?::\d{2})?\s*(?:AM|PM)?)$/i)
    if (!m) { console.warn(`    ⚠️  Could not parse time range "${part}"`); continue }
    const start = parseTimeToken(m[1])
    const end = parseTimeToken(m[2])
    if (!start || !end) continue
    if (!start.meridiem && end.meridiem) start.meridiem = end.meridiem
    if (!end.meridiem && start.meridiem) end.meridiem = start.meridiem
    if (!start.meridiem || !end.meridiem) { console.warn(`    ⚠️  Ambiguous AM/PM in "${part}"`); continue }
    ranges.push({
      startHour: resolveHour(start.hour, start.meridiem), startMinute: start.minute,
      endHour: resolveHour(end.hour, end.meridiem), endMinute: end.minute,
    })
  }
  return ranges
}

/**
 * Returns the same-day-next-month Date, used as the far edge of the sync
 * window (e.g. run on the 1st → window ends on next month's 1st; run on the
 * 15th → window ends on next month's 15th). Since this script only ever runs
 * on the 1st or 15th, there's no month-length edge case to worry about here.
 */
function computeWindowEnd(fromDate) {
  const end = new Date(fromDate)
  end.setMonth(end.getMonth() + 1)
  return end
}

/** Formats a Date as a compact "YYYYMMDD" key for building stable, date-scoped source_ids. */
function dateKey(date) {
  const y = date.getFullYear()
  const m = String(date.getMonth() + 1).padStart(2, '0')
  const d = String(date.getDate()).padStart(2, '0')
  return `${y}${m}${d}`
}

/**
 * Returns the Date of the Nth (or last) occurrence of a given weekday within
 * a specific year/month, or null if that ordinal doesn't exist in that month
 * (e.g. a "5th Thursday" that doesn't occur).
 */
function nthWeekdayOfMonth(year, month, weekdayIndex, ordinal) {
  if (ordinal === 'last') {
    const last = new Date(year, month + 1, 0) // last calendar day of month
    const diff = (last.getDay() - weekdayIndex + 7) % 7
    last.setDate(last.getDate() - diff)
    return last
  }
  const first = new Date(year, month, 1)
  const firstWeekday = first.getDay()
  const dayOffset = (weekdayIndex - firstWeekday + 7) % 7
  const date = 1 + dayOffset + (ordinal - 1) * 7
  const result = new Date(year, month, date)
  if (result.getMonth() !== month) return null // ordinal doesn't exist this month
  return result
}

/** Returns ALL "Nth <weekday>" occurrences within [fromDate, untilDate). `isBlocked(date)` skips closed dates. */
function allNthWeekdayOccurrencesInWindow(ordinal, weekdayIndex, hour, minute, fromDate, untilDate, isBlocked = () => false) {
  const occurrences = []
  const monthSpan = (untilDate.getFullYear() - fromDate.getFullYear()) * 12
    + (untilDate.getMonth() - fromDate.getMonth()) + 1
  for (let i = 0; i <= monthSpan; i++) {
    const probe = new Date(fromDate.getFullYear(), fromDate.getMonth() + i, 1)
    const candidate = nthWeekdayOfMonth(probe.getFullYear(), probe.getMonth(), weekdayIndex, ordinal)
    if (!candidate) continue
    candidate.setHours(hour, minute, 0, 0)
    if (candidate <= fromDate) continue
    if (candidate >= untilDate) continue
    if (isBlocked(candidate)) continue
    occurrences.push(candidate)
  }
  return occurrences
}

/** Returns ALL weekly occurrences of a given weekday+time within [fromDate, untilDate). Used for Type A (structured day-field) schedules. */
function allWeeklyOccurrencesInWindow(weekdayIndex, hour, minute, fromDate, untilDate, isBlocked = () => false) {
  const occurrences = []
  const first = new Date(fromDate)
  first.setHours(hour, minute, 0, 0)
  let diff = (weekdayIndex - fromDate.getDay() + 7) % 7
  if (diff === 0 && first <= fromDate) diff = 7
  first.setDate(first.getDate() + diff)

  let candidate = first
  while (candidate < untilDate) {
    if (!isBlocked(candidate)) occurrences.push(new Date(candidate))
    candidate = new Date(candidate)
    candidate.setDate(candidate.getDate() + 7)
  }
  return occurrences
}

// Ordinal-list separators seen in real data: "1st and 3rd", "1st, 3rd", "1st, 3rd, and 5th"
// (Oxford comma), "2nd & 4th". All four are handled by this one separator pattern.
const ORDINAL_UNIT = '(?:\\d+(?:st|nd|rd|th)|first|second|third|fourth|fifth|last)'
const ORDINAL_SEP = '(?:\\s*,\\s*and\\s*|\\s*,\\s*|\\s+and\\s+|\\s*&\\s*)'

/**
 * Deterministically extracts every "Nth <weekday> of the month at H:MM" clause
 * from a schedule string, WITHOUT pre-splitting on commas first.
 *
 * This matters: real schedule text uses commas two structurally different
 * ways — joining multiple ordinals in ONE clause ("1st, 2nd, 3rd, 4th
 * Wednesdays from 8:00 - 9:00 AM") and separating MULTIPLE clauses ("1st and
 * 4th Thursday ... 7:00 PM, 2nd Friday ... 9:00 AM"). Splitting on every
 * top-level comma first (the earlier approach) breaks the first case into
 * unparseable fragments. Instead this scans the whole string with a
 * non-anchored global regex and lets the ordinal-list grammar itself decide
 * where each clause ends.
 *
 * Also handles, based on real data:
 *   - "of the month" / "of each month" / omitted entirely
 *   - a time with no AM/PM when its paired start/end time has one (borrowed)
 *   - "while supplies last" as an alternative to "until food is gone/runs out",
 *     optionally wrapped in parentheses
 *   - plural weekday names ("Thursdays")
 *
 * Returns { matched: [...], unmatchedText: string } — unmatchedText is
 * whatever's left over after removing every matched clause span, so leftover
 * context (extra notes, a genuinely different phrasing) isn't silently lost.
 */
function parseOrdinalWeekdaySchedule(scheduleText) {
  const clauseRegex = new RegExp(
    `(${ORDINAL_UNIT}(?:${ORDINAL_SEP}${ORDINAL_UNIT})*)` +
    `\\s+(sunday|monday|tuesday|wednesday|thursday|friday|saturday)s?` +
    `\\s+(?:of (?:the|each) month)?[,;]?\\s*(?:from\\s+)?(?:at\\s+)?` +
    `(\\d{1,2}(?::\\d{2})?\\s*(?:AM|PM)?)` +
    `(?:\\s*(?:[-–]|to)\\s*(\\d{1,2}(?::\\d{2})?\\s*(?:AM|PM)?))?` +
    `(?:\\s*\\(?(?:or\\s+)?(?:until food (?:is gone|runs out)|while supplies last)\\)?)?\\.?`,
    'gi'
  )

  const matched = []
  let lastIndex = 0
  const gaps = []

  for (const m of scheduleText.matchAll(clauseRegex)) {
    if (m.index > lastIndex) gaps.push(scheduleText.slice(lastIndex, m.index))
    lastIndex = m.index + m[0].length

    const ordinalTokens = m[1].split(new RegExp(ORDINAL_SEP, 'i')).map(t => t.trim().toLowerCase()).filter(Boolean)
    const ordinals = ordinalTokens.map(t => ORDINAL_MAP[t]).filter(o => o !== undefined)
    const weekdayIndex = DAY_INDEX[m[2].toLowerCase()]

    let start = m[3] ? parseTimeToken(m[3]) : null
    let end = m[4] ? parseTimeToken(m[4]) : null
    if (start && end) {
      if (!start.meridiem && end.meridiem) start.meridiem = end.meridiem
      if (!end.meridiem && start.meridiem) end.meridiem = start.meridiem
    }
    const startOk = start && start.meridiem
    const endOk = end && end.meridiem

    if (ordinals.length === 0 || weekdayIndex === undefined || !startOk) {
      gaps.push(m[0])
      continue
    }

    matched.push({
      ordinals,
      weekdayIndex,
      weekdayName: m[2].toLowerCase(),
      hour: resolveHour(start.hour, start.meridiem),
      minute: start.minute,
      endHour: endOk ? resolveHour(end.hour, end.meridiem) : null,
      endMinute: endOk ? end.minute : null,
      raw: m[0].trim(),
    })
  }
  if (lastIndex < scheduleText.length) gaps.push(scheduleText.slice(lastIndex))

  const unmatchedText = gaps.map(g => g.trim()).filter(g => g && g.replace(/[,;.\s]/g, '') !== '').join(', ')
  return { matched, unmatchedText }
}

/**
 * Extracts clean "M/D[/YY] to/through/- M/D[/YY]" closed-date ranges.
 */
function extractClosureRanges(text) {
  if (!text) return []
  const regex = /(\d{1,2}\/\d{1,2}(?:\/\d{2,4})?)\s*(?:to|through|[-–])\s*(\d{1,2}\/\d{1,2}(?:\/\d{2,4})?)/gi
  const parseDate = str => {
    const parts = str.split('/').map(Number)
    const [mo, d, y = new Date().getFullYear()] = parts
    return new Date(y < 100 ? 2000 + y : y, mo - 1, d)
  }
  const ranges = []
  for (const m of text.matchAll(regex)) {
    const start = parseDate(m[1])
    const end = parseDate(m[2])
    end.setHours(23, 59, 59, 999)
    ranges.push({ start, end })
  }
  return ranges
}

/** Extracts standalone "M/D[/YY]" dates not already part of a "to/through/-" range. */
function extractSingleClosureDates(text) {
  if (!text) return []
  const rangeRegex = /\d{1,2}\/\d{1,2}(?:\/\d{2,4})?\s*(?:to|through|[-–])\s*\d{1,2}\/\d{1,2}(?:\/\d{2,4})?/gi
  const withoutRanges = text.replace(rangeRegex, '')
  const dateRegex = /(\d{1,2})\/(\d{1,2})(?:\/(\d{2,4}))?/g
  const dates = []
  for (const m of withoutRanges.matchAll(dateRegex)) {
    let year = m[3] ? parseInt(m[3]) : null
    if (year !== null && year < 100) year += 2000
    dates.push({ month: parseInt(m[1]) - 1, day: parseInt(m[2]), year })
  }
  return dates
}

/** Checks whether a candidate Date falls in a closed range or matches a standalone closed date. */
function isClosedOnDate(date, ranges, singleDates) {
  if (ranges.some(r => date >= r.start && date <= r.end)) return true
  if (singleDates.some(d => date.getMonth() === d.month && date.getDate() === d.day && (d.year === null || date.getFullYear() === d.year))) return true
  return false
}

/**
 * Decides whether closure/reschedule text needs full AI interpretation rather
 * than simple deterministic date-skipping. Verified against every closure
 * string in a real data pull: clean ranges/dates ("Closed 7/1/26 to 8/17/26.",
 * "Closed 9/7/26") resolve deterministically; anything with a reschedule
 * target, an added date, a resume/reopen note, or a whole-month closure with
 * no day given needs AI ("Closed 7/13. Distributions will resume on 7/27.",
 * "Closed 6/17/26. Added distribution 6/1/26 at 10 AM.", "Closed for summer
 * 5/27 - September").
 */
function needsAiForClosure(closureText) {
  if (!closureText) return false
  const rangeRegex = /\d{1,2}\/\d{1,2}(?:\/\d{2,4})?\s*(?:to|through|[-–])\s*\d{1,2}\/\d{1,2}(?:\/\d{2,4})?/gi
  const withoutRanges = closureText.replace(rangeRegex, '')
  const singleDateRegex = /\d{1,2}\/\d{1,2}(?:\/\d{2,4})?/g
  const withoutDates = withoutRanges.replace(singleDateRegex, '')
  const withoutLabel = withoutDates.replace(/^\s*(closed|closure)?[\s:.,]*$/i, '').trim()
  return withoutLabel.replace(/[\s.,;]+/g, '').length > 0
}

/**
 * Parses "1st/3rd: X | 2nd/4th: Y" style descriptions (seen on several real
 * locations, e.g. "1st/3rd: Mobile Pantry (produce + dry goods) | 2nd/4th:
 * Produce Pantry (lots of produce)") into a map from ordinal number to the
 * segment relevant to that occurrence. Returns null if the description isn't
 * in this shape, so callers can fall back to using the whole description
 * as-is for every occurrence.
 */
function parseOrdinalGroupedDescription(desc) {
  if (!desc) return null
  const segments = desc.split(/\||\n/).map(s => s.trim()).filter(Boolean)
  const map = {}
  let matchedAny = false
  for (const seg of segments) {
    const m = seg.match(/^((?:\d+(?:st|nd|rd|th)\/?)+)\s*:\s*(.+)$/i)
    if (!m) continue
    matchedAny = true
    const tokens = m[1].split('/').map(t => t.trim().toLowerCase()).filter(Boolean)
    for (const tok of tokens) {
      const num = ORDINAL_MAP[tok]
      if (num !== undefined && num !== 'last') map[num] = m[2].trim()
    }
  }
  return matchedAny ? map : null
}

/** Builds a plain-text summary of the structured day fields, for feeding to AI when Type A's closure text is too complex to skip-date deterministically. */
function daysToScheduleSummary(loc) {
  const parts = []
  for (const day of DAY_FIELDS) {
    if (loc[day]?.trim()) {
      const label = day.charAt(0).toUpperCase() + day.slice(1)
      parts.push(`${label}: ${loc[day].trim()}`)
    }
  }
  return parts.join('. ')
}

/**
 * Formats a locally-constructed Date (its getters reflect America/Los_Angeles
 * wall-clock time, since TZ is set at the top of this file) as a "naive"
 * datetime string with NO timezone suffix — e.g. "2026-07-21T09:00:00".
 *
 * This matches an existing, deliberate convention elsewhere in this app (see
 * the admin post-creation form and PublicFeed.jsx's fmtTime/dateKey/
 * parseNaiveDate): timestamps are stored as bare local-time digits, and
 * Postgres labels them UTC on the way in without actually converting them.
 * The frontend reads those raw digits straight back out without
 * re-converting. A genuinely-correct UTC conversion here (what this function
 * replaced) gets relabeled as local time on display and silently shifts
 * every post by the Pacific UTC offset — 7-8 hours forward, which for
 * evening events rolls the calendar date forward by a full day too.
 */
function toNaiveLocalString(date) {
  const y = date.getFullYear()
  const mo = String(date.getMonth() + 1).padStart(2, '0')
  const d = String(date.getDate()).padStart(2, '0')
  const h = String(date.getHours()).padStart(2, '0')
  const mi = String(date.getMinutes()).padStart(2, '0')
  const s = String(date.getSeconds()).padStart(2, '0')
  return `${y}-${mo}-${d}T${h}:${mi}:${s}`
}

/**
 * Validates the AI's returned "YYYY-MM-DDTHH:MM:00" string and passes it
 * through UNCHANGED — it's already in exactly the naive-local format
 * described above, so no conversion belongs here. (This function used to
 * convert to genuine UTC via `.toISOString()`, which was the bug — see
 * toNaiveLocalString's comment.)
 */
function normalizeNaiveLocal(naiveLocalIso) {
  if (!naiveLocalIso) return null
  const d = new Date(naiveLocalIso)
  if (isNaN(d)) return null
  return naiveLocalIso
}

/**
 * Calls OpenAI GPT-4o-mini (via built-in fetch, no package needed) to parse a
 * natural-language schedule into every occurrence that falls within the given
 * window — not just the next one, since each sync run needs to populate
 * roughly a month of upcoming events at once.
 *
 * Used as a fallback when the deterministic ordinal-weekday parser can't
 * recognize the text, or when closure/reschedule text is too semantically
 * loaded for simple date-skipping (see needsAiForClosure). Costs here are low
 * enough that leaning on this fallback freely (rather than flagging for
 * manual review) is the preferred tradeoff.
 *
 * Returns { parsed: true, occurrences: [{start, end}, ...] } or { parsed: false }.
 */
async function parseScheduleWithAI(scheduleText, locationName, closureText, windowStart, windowEnd) {
  if (!process.env.OPENAI_API_KEY) return { parsed: false, occurrences: [] }

  const fmt = d => d.toLocaleDateString('en-US', {
    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric',
    timeZone: 'America/Los_Angeles',
  })
  const today = fmt(new Date())

  const closureLine = closureText
    ? `Closures/reschedules: "${closureText}"`
    : ''

  const prompt = `You are a precise scheduling assistant for food distribution events.

Today (America/Los_Angeles time): ${today}
Window: from ${fmt(windowStart)} through ${fmt(windowEnd)} (exclusive), America/Los_Angeles time
Location: "${locationName}"
Schedule: "${scheduleText}"
${closureLine}

List EVERY occurrence of this schedule that falls within the window above (there may be one, several, or none). Rules:
- Return ONLY valid JSON: a JSON array of occurrences, no markdown or explanation
- Each item: {"start":"YYYY-MM-DDTHH:MM:00","end":"YYYY-MM-DDTHH:MM:00"} — all datetimes ISO 8601, local America/Los_Angeles time, no offset
- If the schedule states an end time or a time range (e.g. "9:00 am - 12:00 pm", "from 2 to 4 pm", "9:00-11:00 AM"), you MUST populate "end" with that time — do not default to null when an end time is present in the text
- Only use null for "end" when the schedule truly gives no end time or duration at all (e.g. just "at 7:00 PM" with nothing after it)
- Only include occurrences strictly after "today" above and strictly before the window end
- Convert "10:00am", "9:30 am", "2:00 p.m." etc. correctly to 24-hour format
- If a listed date falls within a stated closure or cancellation period, omit that occurrence entirely
- If a reschedule note gives a specific replacement date for an occurrence in this window, use the replacement date instead of the normally-computed one
- If the schedule text cannot be parsed at all, return {"parsed":false} instead of an array

Example, schedule states a time range ("9:00 am - 12:00 pm" etc.) — end MUST be populated: [{"start":"2026-08-04T09:00:00","end":"2026-08-04T12:00:00"}]
Example, schedule states only a single time with no range — end is null: [{"start":"2026-08-06T10:00:00","end":null}]
Example, none fall in window: []
Example, unparseable: {"parsed":false}`

  try {
    const res = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${process.env.OPENAI_API_KEY}`,
      },
      body: JSON.stringify({
        model: 'gpt-4o-mini',
        messages: [{ role: 'user', content: prompt }],
        response_format: { type: 'json_object' },
        temperature: 0,
        max_tokens: 2000,
      }),
    })
    const json = await res.json()
    const parsed = JSON.parse(json.choices[0].message.content)

    if (Array.isArray(parsed)) return { parsed: true, occurrences: parsed }
    if (parsed && Array.isArray(parsed.occurrences)) return { parsed: true, occurrences: parsed.occurrences }
    return { parsed: false, occurrences: [] }
  } catch (err) {
    console.error('    ⚠️  OpenAI API error:', err.message)
    return { parsed: false, occurrences: [] }
  }
}

/**
 * Calls the AI parser on a piece of schedule text and builds one post per
 * occurrence it finds within the window.
 *
 * source_id includes the occurrence's date so the same specific occurrence
 * gets the same source_id no matter which sync run (1st-of-month or
 * 15th-of-month) generates it — see the note at the top of this file.
 *
 * Returns an array of post payloads (zero, one, or many).
 */
async function buildAiParsedPost(loc, text, closureText, sharedDesc, base, sourceIdSuffix, windowStart, windowEnd) {
  console.log(`    🤖 AI parsing: "${text}"`)
  const ai = await parseScheduleWithAI(text, loc.name, closureText, windowStart, windowEnd)

  if (!ai.parsed) {
    return [{
      ...base,
      source_id: `${SOURCE_PREFIX}${loc.id}_${sourceIdSuffix}`,
      description: [
        '⚠️ REVIEW REQUIRED — Schedule could not be parsed automatically, even by AI.\n' +
        'Please set the date and time manually before publishing.\n\n' +
        `Raw schedule: ${text}`,
        sharedDesc,
      ].filter(Boolean).join('\n\n'),
      start_time: null,
      end_time: null,
    }]
  }

  const inWindow = ai.occurrences.filter(occ => {
    if (!occ?.start) return false
    const d = new Date(occ.start) // naive local string, interpreted as America/Los_Angeles per TZ set at top of file
    return !isNaN(d) && d > windowStart && d < windowEnd
  })

  if (inWindow.length === 0) {
    return [{
      ...base,
      source_id: `${SOURCE_PREFIX}${loc.id}_${sourceIdSuffix}`,
      description: [`Schedule: ${text}\n\n(No occurrences fall within the current sync window.)`, sharedDesc]
        .filter(Boolean).join('\n\n'),
      start_time: null,
      end_time: null,
    }]
  }

  return inWindow.map(occ => ({
    ...base,
    source_id: `${SOURCE_PREFIX}${loc.id}_${sourceIdSuffix}_${dateKey(new Date(occ.start))}`,
    description: [`Schedule: ${text}`, sharedDesc].filter(Boolean).join('\n\n'),
    start_time: normalizeNaiveLocal(occ.start),
    end_time: normalizeNaiveLocal(occ.end),
  }))
}

// ─── Location → post payload(s) ───────────────────────────────────────────────

/**
 * Converts one Storepoint location into one or more post payloads, covering
 * every occurrence of its schedule within [windowStart, windowEnd).
 *
 * Three schedule types are handled:
 *   A) Day-specific hours (monday/tuesday/… fields) → all weekly occurrences
 *      in the window, per time-range per active day (a day field can have
 *      multiple ranges — see parseTimeRangesInField)
 *   B) "Nth <weekday> of the month" text, deterministically parsed → every
 *      matching occurrence per ordinal/weekday/time clause in the window
 *   C) Anything A/B doesn't fully recognize, or whose closure/reschedule text
 *      is too complex for simple date-skipping (see needsAiForClosure) → AI-
 *      parsed occurrences
 *   D) No schedule data at all → one post, flagged for review
 */
async function locationToPosts(loc, windowStart, windowEnd) {
  const addr = parseAddress(loc.streetaddress)
  const cf = parseCustomFields(loc.custom_fields)
  const scheduleText = (cf[CF_SCHEDULE] ?? '').trim()
  const closureText = (cf[CF_CLOSURES] ?? '').trim()
  const eligibility = (cf[CF_ELIGIBILITY] ?? '').trim()

  const closureRanges = extractClosureRanges(closureText)
  const closureSingleDates = extractSingleClosureDates(closureText)
  const closureNeedsAi = needsAiForClosure(closureText)
  const isBlocked = candidate => isClosedOnDate(candidate, closureRanges, closureSingleDates)

  // Tags: split Storepoint tags, strip day-of-week names (Feeding SD occasionally
  // includes these), always append "Feeding San Diego"
  const FSD_DAY_SET = new Set(['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'])
  const rawTagsFsd = loc.tags ? loc.tags.split(',').map(t => t.trim()).filter(Boolean) : []
  const tags = [
    ...rawTagsFsd.filter(t => !FSD_DAY_SET.has(t)),
    'Feeding San Diego',
  ]

  // sharedDescBase: closure/eligibility notes, WITHOUT loc.description — used when
  // loc.description gets split per-occurrence (see ordinalGroupedDescMap below).
  const sharedLinesBase = []
  if (eligibility) sharedLinesBase.push(`✅ Eligibility & Requirements\n${eligibility}`)
  if (closureText) sharedLinesBase.push(`⚠️ Closure notice: ${closureText}`)
  const sharedDescBase = sharedLinesBase.join('\n\n')

  // sharedDescFull: same, but with loc.description included up front — used
  // everywhere loc.description isn't being split by occurrence.
  const sharedDescFull = [loc.description, sharedDescBase].filter(Boolean).join('\n\n')

  // Common fields shared by every post from this location
  const base = {
    organization_id: FEEDING_SD_ORG_ID,
    title: loc.name,
    location_name: loc.name,
    address: addr.address,
    city: addr.city,
    zip: addr.zip,
    latitude: loc.loc_lat || null,
    longitude: loc.loc_long || null,
    category: 'food-distribution',
    tags,
    organizer_phone: loc.phone?.trim() || null,
    image_url: 'https://feedingsandiego.org/wp-content/uploads/2021/03/Feeding-San-Diego-Logo-Color.png',
    is_active: true,
    is_recurring: false,
    status: 'published',
  }

  const posts = []

  // ── Type A: day-specific structured hours ──────────────────────────────────
  const activeDays = DAY_FIELDS.filter(d => loc[d]?.trim())

  if (activeDays.length > 0) {
    if (closureNeedsAi) {
      // The recurring pattern is structured, but the closure text has semantics
      // (a specific replacement date, an added date, a resume note) that simple
      // date-skipping can't safely resolve — hand the whole thing to AI with a
      // synthesized schedule summary built from the day fields.
      console.log(`    🤖 Structured schedule, but closure text needs interpretation — sending to AI: "${closureText}"`)
      const summary = daysToScheduleSummary(loc)
      return await buildAiParsedPost(loc, summary, closureText, sharedDescFull, base, 'custom', windowStart, windowEnd)
    }

    for (const day of activeDays) {
      const ranges = parseTimeRangesInField(loc[day])
      const dayLabel = day.charAt(0).toUpperCase() + day.slice(1)

      ranges.forEach((tr, rangeIdx) => {
        const occurrences = allWeeklyOccurrencesInWindow(DAY_INDEX[day], tr.startHour, tr.startMinute, windowStart, windowEnd, isBlocked)
        if (occurrences.length === 0) return

        for (const startDt of occurrences) {
          const endDt = new Date(startDt)
          endDt.setHours(tr.endHour, tr.endMinute, 0, 0)

          const descLines = [`Recurring every ${dayLabel}: ${loc[day].trim()}.`]
          if (scheduleText && scheduleText.toLowerCase() !== 'weekly') {
            descLines.push(`Full schedule note: ${scheduleText}`)
          }
          if (sharedDescFull) descLines.push(sharedDescFull)

          posts.push({
            ...base,
            source_id: ranges.length > 1
              ? `${SOURCE_PREFIX}${loc.id}_${day}_r${rangeIdx}_${dateKey(startDt)}`
              : `${SOURCE_PREFIX}${loc.id}_${day}_${dateKey(startDt)}`,
            description: descLines.join('\n\n'),
            start_time: toNaiveLocalString(startDt),
            end_time: toNaiveLocalString(endDt),
          })
        }
      })
    }
    return posts
  }

  // ── Type B: "Nth <weekday> of the month" — parsed deterministically ────────
  if (scheduleText) {
    const { matched, unmatchedText } = parseOrdinalWeekdaySchedule(scheduleText)

    if (matched.length > 0 && closureNeedsAi) {
      console.log(`    🤖 Pattern matched, but closure text needs interpretation — sending to AI: "${closureText}"`)
      return await buildAiParsedPost(loc, scheduleText, closureText, sharedDescFull, base, 'custom', windowStart, windowEnd)
    }

    if (matched.length > 0) {
      console.log(`    🗓️  Deterministically parsed ${matched.length} schedule clause(s)`)

      // "1st/3rd: X | 2nd/4th: Y" style descriptions get split per-occurrence
      // rather than dumped whole into every post.
      const ordinalGroupedDescMap = parseOrdinalGroupedDescription(loc.description)

      for (const clause of matched) {
        const ordinalLabel = ord => ord === 'last' ? 'last' : { 1: '1st', 2: '2nd', 3: '3rd', 4: '4th', 5: '5th' }[ord]
        const weekdayLabel = clause.weekdayName.charAt(0).toUpperCase() + clause.weekdayName.slice(1)

        for (const ordinal of clause.ordinals) {
          const occurrences = allNthWeekdayOccurrencesInWindow(
            ordinal, clause.weekdayIndex, clause.hour, clause.minute,
            windowStart, windowEnd, isBlocked
          )
          if (occurrences.length === 0) continue

          const label = ordinalLabel(ordinal)
          const specificDesc = ordinalGroupedDescMap ? ordinalGroupedDescMap[ordinal] : null

          for (const startDt of occurrences) {
            let endDt = null
            if (clause.endHour !== null) {
              endDt = new Date(startDt)
              endDt.setHours(clause.endHour, clause.endMinute, 0, 0)
            }

            const descLines = [`Recurring: ${label} ${weekdayLabel} of the month — ${clause.raw}.`]
            if (specificDesc) {
              descLines.push(specificDesc)
              if (sharedDescBase) descLines.push(sharedDescBase)
            } else if (sharedDescFull) {
              descLines.push(sharedDescFull)
            }

            posts.push({
              ...base,
              source_id: `${SOURCE_PREFIX}${loc.id}_${clause.weekdayName}_${label}_${dateKey(startDt)}`,
              description: descLines.join('\n\n'),
              start_time: toNaiveLocalString(startDt),
              end_time: endDt ? toNaiveLocalString(endDt) : null,
            })
          }
        }
      }

      // Leftover text the deterministic parser didn't recognize → AI, not a review flag
      if (unmatchedText) {
        posts.push(...await buildAiParsedPost(loc, unmatchedText, closureText, sharedDescFull, base, 'custom', windowStart, windowEnd))
      }

      return posts
    }

    // Nothing matched deterministically at all — hand the whole string to AI
    return await buildAiParsedPost(loc, scheduleText, closureText, sharedDescFull, base, 'custom', windowStart, windowEnd)
  }

  // ── Type D: no usable schedule data — flag for manual review ───────────────
  const descLines = [
    '⚠️ REVIEW REQUIRED — No schedule information could be determined.\n' +
    'Please set the date and time manually before publishing.',
  ]
  if (sharedDescFull) descLines.push(sharedDescFull)

  posts.push({
    ...base,
    source_id: `${SOURCE_PREFIX}${loc.id}_custom`,
    description: descLines.join('\n\n'),
    start_time: null,
    end_time: null,
  })
  return posts
}

// ─── Database operations ──────────────────────────────────────────────────────

/**
 * Upserts a single post.
 *
 * Duplicate rules:
 *   1. Same source_id → update (admin's status and is_active are preserved).
 *   2. Different source_id but same address + start_time → skip (always a duplicate).
 *
 * Returns: 'new' | 'updated' | 'skipped'
 */
async function upsertPost(post) {

  // ── Duplicate guard: address + start_time collision with a different source ──
  if (post.start_time) {
    const { data: dupe } = await supabase
      .from('posts')
      .select('id, title, source_id')
      .eq('address', post.address)
      .eq('start_time', post.start_time)
      .neq('source_id', post.source_id)
      .maybeSingle()

    if (dupe) {
      console.log(
        `    ⏩ Skipped — duplicate of "${dupe.title}" (same address + time)`
      )
      return 'skipped'
    }
  }

  // ── Check for existing record by source_id ──────────────────────────────────
  const { data: existing } = await supabase
    .from('posts')
    .select('id, status, is_active')
    .eq('source_id', post.source_id)
    .maybeSingle()

  if (existing) {
    // UPDATE: refresh all data fields but preserve admin's status and is_active decisions.
    const { status, is_active, ...dataFields } = post
    const { error } = await supabase
      .from('posts')
      .update(dataFields)
      .eq('id', existing.id)

    if (error) {
      console.error(`    ✗ Update failed [${post.source_id}]:`, error.message)
      return 'skipped'
    }
    console.log(`    ↻ Updated: ${post.title}`)
    return 'updated'
  }

  // INSERT: brand-new post, always starts as draft
  const { error } = await supabase.from('posts').insert(post)
  if (error) {
    console.error(`    ✗ Insert failed [${post.source_id}]:`, error.message)
    return 'skipped'
  }
  console.log(`    ✨ New draft: ${post.title}`)
  return 'new'
}

/** Extracts the Storepoint location id embedded at the start of a source_id. */
function extractLocationId(sourceId) {
  const rest = sourceId.slice(SOURCE_PREFIX.length)
  const idx = rest.indexOf('_')
  return idx === -1 ? rest : rest.slice(0, idx)
}

/**
 * Deactivates FSD posts that no longer belong on the live feed, for two
 * distinct reasons:
 *
 *   1. VANISHED — the location itself is no longer in the current Storepoint
 *      batch (left Feeding San Diego's network entirely).
 *
 *   2. STALE — the location still exists, but THIS specific post wasn't
 *      regenerated by the current run, and it isn't simply a past event that
 *      aged out of the window naturally. This catches posts left behind by
 *      an old naming scheme (e.g. `fsd_<id>_custom` from before source_ids
 *      were date-scoped) that will never be regenerated or updated under the
 *      new scheme, as well as an occurrence that got superseded (e.g. a
 *      closure/reschedule that changed which date applies). A post whose
 *      start_time is already in the past relative to this run's window is
 *      left alone — that's expected aging, not staleness.
 */
async function deactivateVanished(processedLocationIds, processedPostIds, windowStart) {
  const { data: activeFsd, error } = await supabase
    .from('posts')
    .select('id, source_id, title, description, start_time')
    .like('source_id', `${SOURCE_PREFIX}%`)
    .eq('is_active', true)

  if (error) {
    console.error('  ✗ Could not fetch existing FSD posts:', error.message)
    return 0
  }

  const stale = (activeFsd ?? []).filter(p => {
    const locationVanished = !processedLocationIds.has(extractLocationId(p.source_id))
    if (locationVanished) return true
    if (processedPostIds.has(p.source_id)) return false // regenerated this run — still current
    if (p.start_time && new Date(p.start_time) < windowStart) return false // already happened — expected aging, not stale
    return true // location is active, but this exact post wasn't regenerated and isn't a past event
  })

  if (stale.length === 0) { console.log('  ✓ No vanished or stale posts.'); return 0 }

  const runDate = new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })

  for (const post of stale) {
    const locationVanished = !processedLocationIds.has(extractLocationId(post.source_id))
    const notice = locationVanished
      ? `[Auto-deactivated ${runDate} — location no longer in Feeding San Diego's directory.]`
      : `[Auto-deactivated ${runDate} — superseded by updated sync data (old source_id format or a changed occurrence). If this looks wrong, check the location's current schedule.]`
    const { error: err } = await supabase
      .from('posts')
      .update({
        is_active: false,
        description: `${notice}\n\n${post.description ?? ''}`.trim(),
      })
      .eq('id', post.id)

    if (err) console.error(`  ✗ Deactivate failed for "${post.title}":`, err.message)
    else console.log(`  🗑️  Deactivated (${locationVanished ? 'vanished' : 'stale'}): ${post.title} [${post.source_id}]`)
  }

  return stale.length
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  console.log(`\n${'─'.repeat(60)}`)
  console.log(`🔄  Feeding San Diego sync — ${new Date().toLocaleString()}`)
  console.log(`${'─'.repeat(60)}\n`)

  // Validate required environment variables
  const missing = ['SUPABASE_URL', 'SUPABASE_SERVICE_ROLE_KEY'].filter(k => !process.env[k])
  if (missing.length) {
    console.error('❌  Missing required environment variables:', missing.join(', '))
    process.exit(1)
  }
  if (!process.env.OPENAI_API_KEY) {
    console.warn('⚠️   OPENAI_API_KEY not set — schedules that need AI parsing will be flagged for manual review.\n')
  }

  // ── 1. Fetch all locations from Storepoint ──────────────────────────────────
  console.log('📡  Fetching from Storepoint API…')
  const res = await fetch(STOREPOINT_URL)
  if (!res.ok) {
    console.error(`❌  Storepoint API returned HTTP ${res.status}`)
    process.exit(1)
  }
  const { results } = await res.json()
  const allLocations = results?.locations ?? []
  console.log(`    ${allLocations.length} total locations received`)

  // ── 2. Filter to East County ZIP codes ─────────────────────────────────────
  const eastCounty = allLocations.filter(loc => {
    const { zip } = parseAddress(loc.streetaddress)
    return EAST_COUNTY_ZIPS.has(zip)
  })
  console.log(`    ${eastCounty.length} East County locations after ZIP filter\n`)

  // ── 3. Compute the sync window ──────────────────────────────────────────────
  // Every occurrence from right now through one month out gets a post — not
  // just the single next one. Running on the 1st and 15th means these windows
  // overlap by design; the overlap is resolved by upsert (same source_id).
  const windowStart = new Date()
  const windowEnd = computeWindowEnd(windowStart)
  console.log(`🗓️  Sync window: ${windowStart.toLocaleDateString('en-US', { timeZone: 'America/Los_Angeles' })} → ${windowEnd.toLocaleDateString('en-US', { timeZone: 'America/Los_Angeles' })}\n`)

  // ── 4. Process each location ────────────────────────────────────────────────
  const processedLocationIds = new Set(eastCounty.map(loc => String(loc.id)))
  const processedPostIds = new Set()
  const counts = { new: 0, updated: 0, skipped: 0 }

  for (const loc of eastCounty) {
    console.log(`📍  ${loc.name}  (${loc.streetaddress})`)

    let posts
    try {
      posts = await locationToPosts(loc, windowStart, windowEnd)
    } catch (err) {
      console.error(`    ✗ Error building post for ${loc.name}:`, err.message)
      continue
    }

    if (posts.length === 0) {
      console.log('    ⚠️  No valid day-slots found — location skipped')
      continue
    }

    for (const post of posts) {
      processedPostIds.add(post.source_id)
      const result = await upsertPost(post)
      counts[result]++
    }
  }

  // ── 5. Deactivate vanished or stale posts ───────────────────────────────────
  console.log('\n🧹  Checking for vanished locations and stale posts…')
  const deactivated = await deactivateVanished(processedLocationIds, processedPostIds, windowStart)

  // ── 6. Summary ──────────────────────────────────────────────────────────────
  console.log(`\n${'─'.repeat(60)}`)
  console.log('✅  Sync complete\n')
  console.log(`    ${eastCounty.length} East County locations processed`)
  console.log(`    ${processedPostIds.size} total post slots evaluated`)
  console.log(`    ${counts.new}       new draft posts created`)
  console.log(`    ${counts.updated}   existing posts refreshed`)
  console.log(`    ${counts.skipped}   skipped (duplicates or errors)`)
  console.log(`    ${deactivated}      deactivated (vanished locations or stale posts)`)
  console.log(`${'─'.repeat(60)}\n`)
}

main().catch(err => {
  console.error('\n❌  Fatal error:', err)
  process.exit(1)
})